import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  getLibraryCatalog,
  installLibrarySkillFromPath,
  updateLibraryTrustPolicy,
} from "./governanceStore.mjs";
import { getManagerHome } from "./runtimeStore.mjs";

const BRIDGE_SLUG = "skills-manager-bridge";
const BRIDGE_VERSION = "0.1.0";

export async function ensureBridgeSkill(request = {}, options = {}) {
  const home = getManagerHome(options);
  const bridgePath = path.join(home, "bridge", BRIDGE_SLUG);
  const baseUrl = String(request.baseUrl || "http://127.0.0.1:5173").replace(/\/$/, "");

  await writeBridgeSkillFiles(bridgePath, baseUrl);
  const installed = await installLibrarySkillFromPath(
    bridgePath,
    {
      sourceType: "system-bridge",
      source: {
        type: "system",
        name: BRIDGE_SLUG,
        generatedBy: "skillsmanager",
        baseUrl,
      },
      invocationMode: "native",
      replace: true,
    },
    options,
  );
  await updateLibraryTrustPolicy(
    installed.record.id,
    {
      status: "trusted",
      notes: "Generated by Skills Manager as the local bridge skill.",
      reviewer: "skillsmanager",
    },
    options,
  );

  const library = await getLibraryCatalog(options);
  const record = library.records.find((item) => item.id === installed.record.id) || installed.record;

  return {
    bridgePath,
    baseUrl,
    record,
  };
}

async function writeBridgeSkillFiles(bridgePath, baseUrl) {
  await mkdir(path.join(bridgePath, "scripts"), { recursive: true });
  await writeFile(
    path.join(bridgePath, "SKILL.md"),
    `---
name: ${BRIDGE_SLUG}
description: Forward agent requests to the local Skills Manager bridge runtime.
version: ${BRIDGE_VERSION}
---

Use this skill when an agent needs to invoke a managed or hybrid skill through Skills Manager.

The local bridge endpoint is:

\`\`\`text
${baseUrl}/api/invocations
\`\`\`

Prepare a JSON payload with \`agentId\`, \`skillId\`, \`policy\`, optional \`resourceKey\`, and \`prompt\`.
Then run:

\`\`\`bash
node scripts/bridge-client.mjs '{"agentId":"codex","skillId":"...","policy":"parallel","prompt":"..."}'
\`\`\`
`,
    "utf8",
  );
  await writeFile(
    path.join(bridgePath, "scripts", "bridge-client.mjs"),
    `const endpoint = process.env.SKILLSMANAGER_BRIDGE_URL || "${baseUrl}/api/invocations";
const payload = JSON.parse(process.argv[2] || "{}");

const response = await fetch(endpoint, {
  method: "POST",
  headers: {
    "content-type": "application/json",
  },
  body: JSON.stringify(payload),
});
const body = await response.text();
if (!response.ok) {
  console.error(body);
  process.exit(1);
}
console.log(body);
`,
    "utf8",
  );
}
